In [4]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
rank_1_tensor = tf.constant([4, 1])
rank_2_tensor = tf.constant([[3, 4], [2, 5]])

print(rank_0_tensor)
print(rank_1_tensor)
print(rank_2_tensor)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor(
[[3 4]
 [2 5]], shape=(2, 2), dtype=int32)


In [6]:
# to numpy array
print(rank_2_tensor.numpy())

[[3 4]
 [2 5]]


In [17]:
tensor_one = tf.constant([[3, 4], [2, 8]])
tensor_two = tf.constant([[2, 3, 1], [1, 4, 1]])

# dot product
print(tf.matmul(tensor_one, tensor_two))

tensor_three = tf.constant([[1, 2], [3, 4]])
# add
print(tf.add(tensor_one, tensor_three))

# multiply
print(tf.multiply(tensor_one, tensor_three))

tf.Tensor(
[[10 25  7]
 [12 38 10]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 4  6]
 [ 5 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 3  8]
 [ 6 32]], shape=(2, 2), dtype=int32)


In [23]:
# find the largest value
print(tf.reduce_max(tensor_one))

print(tensor_one)

# Index of the maximum value along axis 0 (columns)
print(tf.math.argmax(tensor_one))

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(
[[3 4]
 [2 8]], shape=(2, 2), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int64)


In [26]:
tensor_shape = tf.constant([[1], [2], [3]])
print(tf.reshape(tensor_shape, [1, 3]))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [28]:
# ragged tensor

ragged_list = [[0, 1, 2, 3], [4, 5], [6], [7, 8, 9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6], [7, 8, 9]]>


In [29]:
# string tensor
string_tensor = tf.constant(['this', 'is', 'a', 'string'])

print(string_tensor)

tf.Tensor([b'this' b'is' b'a' b'string'], shape=(4,), dtype=string)
